using System;

namespace System
{
	/// <summary>Represents the method that will handle an event. </summary>
	/// <param name="sender">The source of the event.</param>
	/// <param name="e">An <see cref="T:System.EventArgs" /> that contains the event data. </param>
	/// <typeparam name="TEventArgs">The type of the event data generated by the event.</typeparam>
	/// <filterpriority>1</filterpriority>
	// Token: 0x020006EB RID: 1771
	// (Invoke) Token: 0x060043A0 RID: 17312
	[Serializable]
	public delegate void EventHandler<TEventArgs>(object sender, TEventArgs e) where TEventArgs : EventArgs;
}
