using System;

namespace System.Net
{
	/// <summary>The HTTP headers that can be specified in a server response.</summary>
	// Token: 0x02000333 RID: 819
	public enum HttpResponseHeader
	{
		/// <summary>The Cache-Control header, which specifies caching directives that must be obeyed by all caching mechanisms along the request/response chain.</summary>
		// Token: 0x0400117E RID: 4478
		CacheControl,
		/// <summary>The Connection header, which specifies options that are desired for a particular connection.</summary>
		// Token: 0x0400117F RID: 4479
		Connection,
		/// <summary>The Date header, which specifies the date and time at which the response originated.</summary>
		// Token: 0x04001180 RID: 4480
		Date,
		/// <summary>The Keep-Alive header, which specifies a parameter to be used to maintain a persistent connection.</summary>
		// Token: 0x04001181 RID: 4481
		KeepAlive,
		/// <summary>The Pragma header, which specifies implementation-specific directives that might apply to any agent along the request/response chain.</summary>
		// Token: 0x04001182 RID: 4482
		Pragma,
		/// <summary>The Trailer header, which specifies that the indicated header fields are present in the trailer of a message that is encoded with chunked transfer-coding.</summary>
		// Token: 0x04001183 RID: 4483
		Trailer,
		/// <summary>The Transfer-Encoding header, which specifies what (if any) type of transformation has been applied to the message body.</summary>
		// Token: 0x04001184 RID: 4484
		TransferEncoding,
		/// <summary>The Upgrade header, which specifies additional communications protocols that the client supports.</summary>
		// Token: 0x04001185 RID: 4485
		Upgrade,
		/// <summary>The Via header, which specifies intermediate protocols to be used by gateway and proxy agents.</summary>
		// Token: 0x04001186 RID: 4486
		Via,
		/// <summary>The Warning header, which specifies additional information about that status or transformation of a message that might not be reflected in the message.</summary>
		// Token: 0x04001187 RID: 4487
		Warning,
		/// <summary>The Allow header, which specifies the set of HTTP methods that are supported.</summary>
		// Token: 0x04001188 RID: 4488
		Allow,
		/// <summary>The Content-Length header, which specifies the length, in bytes, of the accompanying body data.</summary>
		// Token: 0x04001189 RID: 4489
		ContentLength,
		/// <summary>The Content-Type header, which specifies the MIME type of the accompanying body data.</summary>
		// Token: 0x0400118A RID: 4490
		ContentType,
		/// <summary>The Content-Encoding header, which specifies the encodings that have been applied to the accompanying body data.</summary>
		// Token: 0x0400118B RID: 4491
		ContentEncoding,
		/// <summary>The Content-Langauge header, which specifies the natural language or languages of the accompanying body data.</summary>
		// Token: 0x0400118C RID: 4492
		ContentLanguage,
		/// <summary>The Content-Location header, which specifies a URI from which the accompanying body can be obtained.</summary>
		// Token: 0x0400118D RID: 4493
		ContentLocation,
		/// <summary>The Content-MD5 header, which specifies the MD5 digest of the accompanying body data, for the purpose of providing an end-to-end message integrity check.</summary>
		// Token: 0x0400118E RID: 4494
		ContentMd5,
		/// <summary>The Range header, which specifies the subrange or subranges of the response that the client requests be returned in lieu of the entire response.</summary>
		// Token: 0x0400118F RID: 4495
		ContentRange,
		/// <summary>The Expires header, which specifies the date and time after which the accompanying body data should be considered stale.</summary>
		// Token: 0x04001190 RID: 4496
		Expires,
		/// <summary>The Last-Modified header, which specifies the date and time at which the accompanying body data was last modified.</summary>
		// Token: 0x04001191 RID: 4497
		LastModified,
		/// <summary>The Accept-Ranges header, which specifies the range that is accepted by the server.</summary>
		// Token: 0x04001192 RID: 4498
		AcceptRanges,
		/// <summary>The Age header, which specifies the time, in seconds, since the response was generated by the originating server.</summary>
		// Token: 0x04001193 RID: 4499
		Age,
		/// <summary>The Etag header, which specifies the current value for the requested variant. </summary>
		// Token: 0x04001194 RID: 4500
		ETag,
		/// <summary>The Location header, which specifies a URI to which the client is redirected to obtain the requested resource.</summary>
		// Token: 0x04001195 RID: 4501
		Location,
		/// <summary>The Proxy-Authenticate header, which specifies that the client must authenticate itself to a proxy.</summary>
		// Token: 0x04001196 RID: 4502
		ProxyAuthenticate,
		/// <summary>The Retry-After header, which specifies a time (in seconds), or a date and time, after which the client can retry its request.</summary>
		// Token: 0x04001197 RID: 4503
		RetryAfter,
		/// <summary>The Server header, which specifies information about the originating server agent.</summary>
		// Token: 0x04001198 RID: 4504
		Server,
		/// <summary>The Set-Cookie header, which specifies cookie data that is presented to the client.</summary>
		// Token: 0x04001199 RID: 4505
		SetCookie,
		/// <summary>The Vary header, which specifies the request headers that are used to determine whether a cached response is fresh.</summary>
		// Token: 0x0400119A RID: 4506
		Vary,
		/// <summary>The WWW-Authenticate header, which specifies that the client must authenticate itself to the server.</summary>
		// Token: 0x0400119B RID: 4507
		WwwAuthenticate
	}
}
