using System;
using System.ComponentModel;

namespace System.Text.RegularExpressions
{
	/// <summary>The <see cref="T:System.Text.RegularExpressions.RegexRunner" /> class is the base class for compiled regular expressions.</summary>
	// Token: 0x020004AB RID: 1195
	[global::System.MonoTODO("RegexRunner is not supported by Mono.")]
	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	public abstract class RegexRunner
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Text.RegularExpressions.RegexRunner" /> class. </summary>
		// Token: 0x06002A5E RID: 10846 RVA: 0x000021C3 File Offset: 0x000003C3
		[global::System.MonoTODO]
		protected internal RegexRunner()
		{
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x06002A5F RID: 10847
		protected abstract bool FindFirstChar();

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x06002A60 RID: 10848
		protected abstract void Go();

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x06002A61 RID: 10849
		protected abstract void InitTrackCount();

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x06002A62 RID: 10850 RVA: 0x00002664 File Offset: 0x00000864
		[global::System.MonoTODO]
		protected void Capture(int capnum, int start, int end)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. Determines whether a character is in a character class.</summary>
		/// <returns>true if the <paramref name="ch" /> parameter is in the character class specified by the <paramref name="charClass" /> parameter.</returns>
		/// <param name="ch">A character to test.</param>
		/// <param name="charClass">The internal name of a character class.</param>
		// Token: 0x06002A63 RID: 10851 RVA: 0x00002664 File Offset: 0x00000864
		[global::System.MonoTODO]
		protected static bool CharInClass(char ch, string charClass)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x06002A64 RID: 10852 RVA: 0x00002664 File Offset: 0x00000864
		[global::System.MonoTODO]
		protected static bool CharInSet(char ch, string set, string category)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x06002A65 RID: 10853 RVA: 0x00002664 File Offset: 0x00000864
		[global::System.MonoTODO]
		protected void Crawl(int i)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x06002A66 RID: 10854 RVA: 0x00002664 File Offset: 0x00000864
		[global::System.MonoTODO]
		protected int Crawlpos()
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x06002A67 RID: 10855 RVA: 0x00002664 File Offset: 0x00000864
		[global::System.MonoTODO]
		protected void DoubleCrawl()
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x06002A68 RID: 10856 RVA: 0x00002664 File Offset: 0x00000864
		[global::System.MonoTODO]
		protected void DoubleStack()
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x06002A69 RID: 10857 RVA: 0x00002664 File Offset: 0x00000864
		[global::System.MonoTODO]
		protected void DoubleTrack()
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x06002A6A RID: 10858 RVA: 0x00002664 File Offset: 0x00000864
		[global::System.MonoTODO]
		protected void EnsureStorage()
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x06002A6B RID: 10859 RVA: 0x00002664 File Offset: 0x00000864
		[global::System.MonoTODO]
		protected bool IsBoundary(int index, int startpos, int endpos)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x06002A6C RID: 10860 RVA: 0x00002664 File Offset: 0x00000864
		[global::System.MonoTODO]
		protected bool IsECMABoundary(int index, int startpos, int endpos)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x06002A6D RID: 10861 RVA: 0x00002664 File Offset: 0x00000864
		[global::System.MonoTODO]
		protected bool IsMatched(int cap)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x06002A6E RID: 10862 RVA: 0x00002664 File Offset: 0x00000864
		[global::System.MonoTODO]
		protected int MatchIndex(int cap)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x06002A6F RID: 10863 RVA: 0x00002664 File Offset: 0x00000864
		[global::System.MonoTODO]
		protected int MatchLength(int cap)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x06002A70 RID: 10864 RVA: 0x00002664 File Offset: 0x00000864
		[global::System.MonoTODO]
		protected int Popcrawl()
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x06002A71 RID: 10865 RVA: 0x00002664 File Offset: 0x00000864
		[global::System.MonoTODO]
		protected void TransferCapture(int capnum, int uncapnum, int start, int end)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		// Token: 0x06002A72 RID: 10866 RVA: 0x00002664 File Offset: 0x00000864
		[global::System.MonoTODO]
		protected void Uncapture()
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x06002A73 RID: 10867 RVA: 0x00002664 File Offset: 0x00000864
		protected internal Match Scan(Regex regex, string text, int textbeg, int textend, int textstart, int prevlen, bool quick)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A4D RID: 6733
		[global::System.MonoTODO]
		protected internal int[] runcrawl;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A4E RID: 6734
		[global::System.MonoTODO]
		protected internal int runcrawlpos;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A4F RID: 6735
		[global::System.MonoTODO]
		protected internal Match runmatch;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A50 RID: 6736
		[global::System.MonoTODO]
		protected internal Regex runregex;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A51 RID: 6737
		[global::System.MonoTODO]
		protected internal int[] runstack;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A52 RID: 6738
		[global::System.MonoTODO]
		protected internal int runstackpos;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A53 RID: 6739
		[global::System.MonoTODO]
		protected internal string runtext;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A54 RID: 6740
		[global::System.MonoTODO]
		protected internal int runtextbeg;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A55 RID: 6741
		[global::System.MonoTODO]
		protected internal int runtextend;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A56 RID: 6742
		[global::System.MonoTODO]
		protected internal int runtextpos;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A57 RID: 6743
		[global::System.MonoTODO]
		protected internal int runtextstart;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A58 RID: 6744
		[global::System.MonoTODO]
		protected internal int[] runtrack;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A59 RID: 6745
		[global::System.MonoTODO]
		protected internal int runtrackcount;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A5A RID: 6746
		[global::System.MonoTODO]
		protected internal int runtrackpos;
	}
}
