using System;

namespace System.CodeDom.Compiler
{
	/// <summary>Identifies code generated by a tool. This class cannot be inherited.</summary>
	// Token: 0x02000088 RID: 136
	[AttributeUsage(AttributeTargets.All, Inherited = false, AllowMultiple = false)]
	public sealed class GeneratedCodeAttribute : Attribute
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.CodeDom.Compiler.GeneratedCodeAttribute" /> class specifying the name and version of the tool that generated the code.</summary>
		/// <param name="tool">The name of the tool that generated the code.</param>
		/// <param name="version">The version of the tool that generated the code.</param>
		// Token: 0x0600059F RID: 1439 RVA: 0x00005DE9 File Offset: 0x00003FE9
		public GeneratedCodeAttribute(string tool, string version)
		{
			this.tool = tool;
			this.version = version;
		}

		/// <summary>Gets the name of the tool that generated the code.</summary>
		/// <returns>The name of the tool that generated to code.</returns>
		// Token: 0x17000119 RID: 281
		// (get) Token: 0x060005A0 RID: 1440 RVA: 0x00005DFF File Offset: 0x00003FFF
		public string Tool
		{
			get
			{
				return this.tool;
			}
		}

		/// <summary>Gets the version of the tool that generated the code.</summary>
		/// <returns>The version of the tool that generated the code.</returns>
		// Token: 0x1700011A RID: 282
		// (get) Token: 0x060005A1 RID: 1441 RVA: 0x00005E07 File Offset: 0x00004007
		public string Version
		{
			get
			{
				return this.version;
			}
		}

		// Token: 0x04000161 RID: 353
		private string tool;

		// Token: 0x04000162 RID: 354
		private string version;
	}
}
