using System;
using System.Collections;
using System.Runtime.InteropServices;

namespace UnityEngine
{
	/// <summary>
	///   <para>Describes a collision.</para>
	/// </summary>
	// Token: 0x020000FD RID: 253
	[StructLayout(LayoutKind.Sequential)]
	public class Collision
	{
		/// <summary>
		///   <para>The relative linear velocity of the two colliding objects (Read Only).</para>
		/// </summary>
		// Token: 0x170003B6 RID: 950
		// (get) Token: 0x06000E7D RID: 3709 RVA: 0x00006DAB File Offset: 0x00004FAB
		public Vector3 relativeVelocity
		{
			get
			{
				return this.m_RelativeVelocity;
			}
		}

		/// <summary>
		///   <para>The Rigidbody we hit (Read Only). This is null if the object we hit is a collider with no rigidbody attached.</para>
		/// </summary>
		// Token: 0x170003B7 RID: 951
		// (get) Token: 0x06000E7E RID: 3710 RVA: 0x00006DB3 File Offset: 0x00004FB3
		public Rigidbody rigidbody
		{
			get
			{
				return this.m_Rigidbody;
			}
		}

		/// <summary>
		///   <para>The Collider we hit (Read Only).</para>
		/// </summary>
		// Token: 0x170003B8 RID: 952
		// (get) Token: 0x06000E7F RID: 3711 RVA: 0x00006DBB File Offset: 0x00004FBB
		public Collider collider
		{
			get
			{
				return this.m_Collider;
			}
		}

		/// <summary>
		///   <para>The Transform of the object we hit (Read Only).</para>
		/// </summary>
		// Token: 0x170003B9 RID: 953
		// (get) Token: 0x06000E80 RID: 3712 RVA: 0x00006DC3 File Offset: 0x00004FC3
		public Transform transform
		{
			get
			{
				return (!(this.rigidbody != null)) ? this.collider.transform : this.rigidbody.transform;
			}
		}

		/// <summary>
		///   <para>The GameObject whose collider we are colliding with. (Read Only).</para>
		/// </summary>
		// Token: 0x170003BA RID: 954
		// (get) Token: 0x06000E81 RID: 3713 RVA: 0x00006DF1 File Offset: 0x00004FF1
		public GameObject gameObject
		{
			get
			{
				return (!(this.m_Rigidbody != null)) ? this.m_Collider.gameObject : this.m_Rigidbody.gameObject;
			}
		}

		/// <summary>
		///   <para>The contact points generated by the physics engine.</para>
		/// </summary>
		// Token: 0x170003BB RID: 955
		// (get) Token: 0x06000E82 RID: 3714 RVA: 0x00006E1F File Offset: 0x0000501F
		public ContactPoint[] contacts
		{
			get
			{
				return this.m_Contacts;
			}
		}

		// Token: 0x06000E83 RID: 3715 RVA: 0x00006E27 File Offset: 0x00005027
		public virtual IEnumerator GetEnumerator()
		{
			return this.contacts.GetEnumerator();
		}

		/// <summary>
		///   <para>The total impulse applied to this contact pair to resolve the collision.</para>
		/// </summary>
		// Token: 0x170003BC RID: 956
		// (get) Token: 0x06000E84 RID: 3716 RVA: 0x00006E34 File Offset: 0x00005034
		public Vector3 impulse
		{
			get
			{
				return this.m_Impulse;
			}
		}

		// Token: 0x170003BD RID: 957
		// (get) Token: 0x06000E85 RID: 3717 RVA: 0x00006E3C File Offset: 0x0000503C
		[Obsolete("Use Collision.relativeVelocity instead.", false)]
		public Vector3 impactForceSum
		{
			get
			{
				return this.relativeVelocity;
			}
		}

		// Token: 0x170003BE RID: 958
		// (get) Token: 0x06000E86 RID: 3718 RVA: 0x00005F24 File Offset: 0x00004124
		[Obsolete("Will always return zero.", false)]
		public Vector3 frictionForceSum
		{
			get
			{
				return Vector3.zero;
			}
		}

		// Token: 0x170003BF RID: 959
		// (get) Token: 0x06000E87 RID: 3719 RVA: 0x00006E44 File Offset: 0x00005044
		[Obsolete("Please use Collision.rigidbody, Collision.transform or Collision.collider instead", false)]
		public Component other
		{
			get
			{
				return (!(this.m_Rigidbody != null)) ? this.m_Collider : this.m_Rigidbody;
			}
		}

		// Token: 0x040002F1 RID: 753
		internal Vector3 m_Impulse;

		// Token: 0x040002F2 RID: 754
		internal Vector3 m_RelativeVelocity;

		// Token: 0x040002F3 RID: 755
		internal Rigidbody m_Rigidbody;

		// Token: 0x040002F4 RID: 756
		internal Collider m_Collider;

		// Token: 0x040002F5 RID: 757
		internal ContactPoint[] m_Contacts;
	}
}
