using System;
using System.Runtime.InteropServices;

namespace System.Runtime.CompilerServices
{
	/// <summary>Controls the strictness of the code generated by the common language runtime's just-in-time (JIT) compiler.</summary>
	// Token: 0x02000326 RID: 806
	[AttributeUsage(AttributeTargets.Assembly | AttributeTargets.Module | AttributeTargets.Class | AttributeTargets.Method)]
	[ComVisible(true)]
	[Serializable]
	public class CompilationRelaxationsAttribute : Attribute
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Runtime.CompilerServices.CompilationRelaxationsAttribute" /> class with the specified compilation relaxations.</summary>
		/// <param name="relaxations">The compilation relaxations. </param>
		// Token: 0x06002899 RID: 10393 RVA: 0x00091D28 File Offset: 0x0008FF28
		public CompilationRelaxationsAttribute(int relaxations)
		{
			this.relax = relaxations;
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Runtime.CompilerServices.CompilationRelaxationsAttribute" /> class with the specified <see cref="T:System.Runtime.CompilerServices.CompilationRelaxations" /> value. </summary>
		/// <param name="relaxations">One of the <see cref="T:System.Runtime.CompilerServices.CompilationRelaxations" /> values.</param>
		// Token: 0x0600289A RID: 10394 RVA: 0x00091D38 File Offset: 0x0008FF38
		public CompilationRelaxationsAttribute(CompilationRelaxations relaxations)
		{
			this.relax = (int)relaxations;
		}

		/// <summary>Gets the compilation relaxations specified when the current object was constructed.</summary>
		/// <returns>The compilation relaxations specified when the current object was constructed.Use the <see cref="T:System.Runtime.CompilerServices.CompilationRelaxations" /> enumeration with the <see cref="P:System.Runtime.CompilerServices.CompilationRelaxationsAttribute.CompilationRelaxations" /> property.</returns>
		// Token: 0x17000745 RID: 1861
		// (get) Token: 0x0600289B RID: 10395 RVA: 0x00091D48 File Offset: 0x0008FF48
		public int CompilationRelaxations
		{
			get
			{
				return this.relax;
			}
		}

		// Token: 0x04001086 RID: 4230
		private int relax;
	}
}
