using System;
using System.CodeDom;
using System.CodeDom.Compiler;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Reflection;
using System.Text;

namespace Mono.CSharp
{
	// Token: 0x0200000C RID: 12
	internal class CSharpCodeGenerator : global::System.CodeDom.Compiler.CodeGenerator
	{
		// Token: 0x0600001F RID: 31 RVA: 0x00002292 File Offset: 0x00000492
		public CSharpCodeGenerator()
		{
			this.dont_write_semicolon = false;
		}

		// Token: 0x06000020 RID: 32 RVA: 0x000022A1 File Offset: 0x000004A1
		public CSharpCodeGenerator(IDictionary<string, string> providerOptions)
		{
			this.providerOptions = providerOptions;
		}

		// Token: 0x17000003 RID: 3
		// (get) Token: 0x06000022 RID: 34 RVA: 0x000022B0 File Offset: 0x000004B0
		protected IDictionary<string, string> ProviderOptions
		{
			get
			{
				return this.providerOptions;
			}
		}

		// Token: 0x17000004 RID: 4
		// (get) Token: 0x06000023 RID: 35 RVA: 0x000022B8 File Offset: 0x000004B8
		protected override string NullToken
		{
			get
			{
				return "null";
			}
		}

		// Token: 0x06000024 RID: 36 RVA: 0x0001FCD4 File Offset: 0x0001DED4
		protected override void GenerateArrayCreateExpression(global::System.CodeDom.CodeArrayCreateExpression expression)
		{
			TextWriter output = base.Output;
			output.Write("new ");
			global::System.CodeDom.CodeExpressionCollection initializers = expression.Initializers;
			global::System.CodeDom.CodeTypeReference codeTypeReference = expression.CreateType;
			if (initializers.Count > 0)
			{
				this.OutputType(codeTypeReference);
				if (expression.CreateType.ArrayRank == 0)
				{
					output.Write("[]");
				}
				this.OutputStartBrace();
				base.Indent++;
				this.OutputExpressionList(initializers, true);
				base.Indent--;
				output.Write("}");
			}
			else
			{
				for (global::System.CodeDom.CodeTypeReference codeTypeReference2 = codeTypeReference.ArrayElementType; codeTypeReference2 != null; codeTypeReference2 = codeTypeReference2.ArrayElementType)
				{
					codeTypeReference = codeTypeReference2;
				}
				this.OutputType(codeTypeReference);
				output.Write('[');
				global::System.CodeDom.CodeExpression sizeExpression = expression.SizeExpression;
				if (sizeExpression != null)
				{
					base.GenerateExpression(sizeExpression);
				}
				else
				{
					output.Write(expression.Size);
				}
				output.Write(']');
			}
		}

		// Token: 0x06000025 RID: 37 RVA: 0x000022BF File Offset: 0x000004BF
		protected override void GenerateBaseReferenceExpression(global::System.CodeDom.CodeBaseReferenceExpression expression)
		{
			base.Output.Write("base");
		}

		// Token: 0x06000026 RID: 38 RVA: 0x0001FDC4 File Offset: 0x0001DFC4
		protected override void GenerateCastExpression(global::System.CodeDom.CodeCastExpression expression)
		{
			TextWriter output = base.Output;
			output.Write("((");
			this.OutputType(expression.TargetType);
			output.Write(")(");
			base.GenerateExpression(expression.Expression);
			output.Write("))");
		}

		// Token: 0x06000027 RID: 39 RVA: 0x0001FE14 File Offset: 0x0001E014
		protected override void GenerateCompileUnitStart(global::System.CodeDom.CodeCompileUnit compileUnit)
		{
			this.GenerateComment(new global::System.CodeDom.CodeComment("------------------------------------------------------------------------------"));
			this.GenerateComment(new global::System.CodeDom.CodeComment(" <autogenerated>"));
			this.GenerateComment(new global::System.CodeDom.CodeComment("     This code was generated by a tool."));
			this.GenerateComment(new global::System.CodeDom.CodeComment("     Mono Runtime Version: " + Environment.Version));
			this.GenerateComment(new global::System.CodeDom.CodeComment(string.Empty));
			this.GenerateComment(new global::System.CodeDom.CodeComment("     Changes to this file may cause incorrect behavior and will be lost if "));
			this.GenerateComment(new global::System.CodeDom.CodeComment("     the code is regenerated."));
			this.GenerateComment(new global::System.CodeDom.CodeComment(" </autogenerated>"));
			this.GenerateComment(new global::System.CodeDom.CodeComment("------------------------------------------------------------------------------"));
			base.Output.WriteLine();
			base.GenerateCompileUnitStart(compileUnit);
		}

		// Token: 0x06000028 RID: 40 RVA: 0x0001FED0 File Offset: 0x0001E0D0
		protected override void GenerateCompileUnit(global::System.CodeDom.CodeCompileUnit compileUnit)
		{
			this.GenerateCompileUnitStart(compileUnit);
			if (compileUnit.AssemblyCustomAttributes.Count > 0)
			{
				this.OutputAttributes(compileUnit.AssemblyCustomAttributes, "assembly: ", false);
				base.Output.WriteLine(string.Empty);
			}
			foreach (object obj in compileUnit.Namespaces)
			{
				global::System.CodeDom.CodeNamespace codeNamespace = (global::System.CodeDom.CodeNamespace)obj;
				this.GenerateNamespace(codeNamespace);
			}
			this.GenerateCompileUnitEnd(compileUnit);
		}

		// Token: 0x06000029 RID: 41 RVA: 0x000022D1 File Offset: 0x000004D1
		protected override void GenerateDefaultValueExpression(global::System.CodeDom.CodeDefaultValueExpression e)
		{
			base.Output.Write("default(");
			this.OutputType(e.Type);
			base.Output.Write(')');
		}

		// Token: 0x0600002A RID: 42 RVA: 0x0001FF74 File Offset: 0x0001E174
		protected override void GenerateDelegateCreateExpression(global::System.CodeDom.CodeDelegateCreateExpression expression)
		{
			TextWriter output = base.Output;
			output.Write("new ");
			this.OutputType(expression.DelegateType);
			output.Write('(');
			global::System.CodeDom.CodeExpression targetObject = expression.TargetObject;
			if (targetObject != null)
			{
				base.GenerateExpression(targetObject);
				base.Output.Write('.');
			}
			output.Write(this.GetSafeName(expression.MethodName));
			output.Write(')');
		}

		// Token: 0x0600002B RID: 43 RVA: 0x0001FFE4 File Offset: 0x0001E1E4
		protected override void GenerateFieldReferenceExpression(global::System.CodeDom.CodeFieldReferenceExpression expression)
		{
			global::System.CodeDom.CodeExpression targetObject = expression.TargetObject;
			if (targetObject != null)
			{
				base.GenerateExpression(targetObject);
				base.Output.Write('.');
			}
			base.Output.Write(this.GetSafeName(expression.FieldName));
		}

		// Token: 0x0600002C RID: 44 RVA: 0x000022FC File Offset: 0x000004FC
		protected override void GenerateArgumentReferenceExpression(global::System.CodeDom.CodeArgumentReferenceExpression expression)
		{
			base.Output.Write(this.GetSafeName(expression.ParameterName));
		}

		// Token: 0x0600002D RID: 45 RVA: 0x00002315 File Offset: 0x00000515
		protected override void GenerateVariableReferenceExpression(global::System.CodeDom.CodeVariableReferenceExpression expression)
		{
			base.Output.Write(this.GetSafeName(expression.VariableName));
		}

		// Token: 0x0600002E RID: 46 RVA: 0x0002002C File Offset: 0x0001E22C
		protected override void GenerateIndexerExpression(global::System.CodeDom.CodeIndexerExpression expression)
		{
			TextWriter output = base.Output;
			base.GenerateExpression(expression.TargetObject);
			output.Write('[');
			this.OutputExpressionList(expression.Indices);
			output.Write(']');
		}

		// Token: 0x0600002F RID: 47 RVA: 0x00020068 File Offset: 0x0001E268
		protected override void GenerateArrayIndexerExpression(global::System.CodeDom.CodeArrayIndexerExpression expression)
		{
			TextWriter output = base.Output;
			base.GenerateExpression(expression.TargetObject);
			output.Write('[');
			this.OutputExpressionList(expression.Indices);
			output.Write(']');
		}

		// Token: 0x06000030 RID: 48 RVA: 0x0000232E File Offset: 0x0000052E
		protected override void GenerateSnippetExpression(global::System.CodeDom.CodeSnippetExpression expression)
		{
			base.Output.Write(expression.Value);
		}

		// Token: 0x06000031 RID: 49 RVA: 0x000200A4 File Offset: 0x0001E2A4
		protected override void GenerateMethodInvokeExpression(global::System.CodeDom.CodeMethodInvokeExpression expression)
		{
			TextWriter output = base.Output;
			this.GenerateMethodReferenceExpression(expression.Method);
			output.Write('(');
			this.OutputExpressionList(expression.Parameters);
			output.Write(')');
		}

		// Token: 0x06000032 RID: 50 RVA: 0x000200E0 File Offset: 0x0001E2E0
		protected override void GenerateMethodReferenceExpression(global::System.CodeDom.CodeMethodReferenceExpression expression)
		{
			if (expression.TargetObject != null)
			{
				base.GenerateExpression(expression.TargetObject);
				base.Output.Write('.');
			}
			base.Output.Write(this.GetSafeName(expression.MethodName));
			if (expression.TypeArguments.Count > 0)
			{
				base.Output.Write(this.GetTypeArguments(expression.TypeArguments));
			}
		}

		// Token: 0x06000033 RID: 51 RVA: 0x00002341 File Offset: 0x00000541
		protected override void GenerateEventReferenceExpression(global::System.CodeDom.CodeEventReferenceExpression expression)
		{
			if (expression.TargetObject != null)
			{
				base.GenerateExpression(expression.TargetObject);
				base.Output.Write('.');
			}
			base.Output.Write(this.GetSafeName(expression.EventName));
		}

		// Token: 0x06000034 RID: 52 RVA: 0x0000237E File Offset: 0x0000057E
		protected override void GenerateDelegateInvokeExpression(global::System.CodeDom.CodeDelegateInvokeExpression expression)
		{
			if (expression.TargetObject != null)
			{
				base.GenerateExpression(expression.TargetObject);
			}
			base.Output.Write('(');
			this.OutputExpressionList(expression.Parameters);
			base.Output.Write(')');
		}

		// Token: 0x06000035 RID: 53 RVA: 0x00020150 File Offset: 0x0001E350
		protected override void GenerateObjectCreateExpression(global::System.CodeDom.CodeObjectCreateExpression expression)
		{
			base.Output.Write("new ");
			this.OutputType(expression.CreateType);
			base.Output.Write('(');
			this.OutputExpressionList(expression.Parameters);
			base.Output.Write(')');
		}

		// Token: 0x06000036 RID: 54 RVA: 0x000201A0 File Offset: 0x0001E3A0
		protected override void GeneratePropertyReferenceExpression(global::System.CodeDom.CodePropertyReferenceExpression expression)
		{
			global::System.CodeDom.CodeExpression targetObject = expression.TargetObject;
			if (targetObject != null)
			{
				base.GenerateExpression(targetObject);
				base.Output.Write('.');
			}
			base.Output.Write(this.GetSafeName(expression.PropertyName));
		}

		// Token: 0x06000037 RID: 55 RVA: 0x000023BD File Offset: 0x000005BD
		protected override void GeneratePropertySetValueReferenceExpression(global::System.CodeDom.CodePropertySetValueReferenceExpression expression)
		{
			base.Output.Write("value");
		}

		// Token: 0x06000038 RID: 56 RVA: 0x000023CF File Offset: 0x000005CF
		protected override void GenerateThisReferenceExpression(global::System.CodeDom.CodeThisReferenceExpression expression)
		{
			base.Output.Write("this");
		}

		// Token: 0x06000039 RID: 57 RVA: 0x000023E1 File Offset: 0x000005E1
		protected override void GenerateExpressionStatement(global::System.CodeDom.CodeExpressionStatement statement)
		{
			base.GenerateExpression(statement.Expression);
			if (this.dont_write_semicolon)
			{
				return;
			}
			base.Output.WriteLine(';');
		}

		// Token: 0x0600003A RID: 58 RVA: 0x000201E8 File Offset: 0x0001E3E8
		protected override void GenerateIterationStatement(global::System.CodeDom.CodeIterationStatement statement)
		{
			TextWriter output = base.Output;
			this.dont_write_semicolon = true;
			output.Write("for (");
			base.GenerateStatement(statement.InitStatement);
			output.Write("; ");
			base.GenerateExpression(statement.TestExpression);
			output.Write("; ");
			base.GenerateStatement(statement.IncrementStatement);
			output.Write(")");
			this.dont_write_semicolon = false;
			this.OutputStartBrace();
			base.Indent++;
			base.GenerateStatements(statement.Statements);
			base.Indent--;
			output.WriteLine('}');
		}

		// Token: 0x0600003B RID: 59 RVA: 0x00020290 File Offset: 0x0001E490
		protected override void GenerateThrowExceptionStatement(global::System.CodeDom.CodeThrowExceptionStatement statement)
		{
			base.Output.Write("throw");
			if (statement.ToThrow != null)
			{
				base.Output.Write(' ');
				base.GenerateExpression(statement.ToThrow);
			}
			base.Output.WriteLine(";");
		}

		// Token: 0x0600003C RID: 60 RVA: 0x000202E4 File Offset: 0x0001E4E4
		protected override void GenerateComment(global::System.CodeDom.CodeComment comment)
		{
			TextWriter output = base.Output;
			string text;
			if (comment.DocComment)
			{
				text = "///";
			}
			else
			{
				text = "//";
			}
			output.Write(text);
			output.Write(' ');
			string text2 = comment.Text;
			for (int i = 0; i < text2.Length; i++)
			{
				output.Write(text2[i]);
				if (text2[i] == '\r')
				{
					if (i >= text2.Length - 1 || text2[i + 1] != '\n')
					{
						output.Write(text);
					}
				}
				else if (text2[i] == '\n')
				{
					output.Write(text);
				}
			}
			output.WriteLine();
		}

		// Token: 0x0600003D RID: 61 RVA: 0x000203A8 File Offset: 0x0001E5A8
		protected override void GenerateMethodReturnStatement(global::System.CodeDom.CodeMethodReturnStatement statement)
		{
			TextWriter output = base.Output;
			if (statement.Expression != null)
			{
				output.Write("return ");
				base.GenerateExpression(statement.Expression);
				output.WriteLine(";");
			}
			else
			{
				output.WriteLine("return;");
			}
		}

		// Token: 0x0600003E RID: 62 RVA: 0x000203FC File Offset: 0x0001E5FC
		protected override void GenerateConditionStatement(global::System.CodeDom.CodeConditionStatement statement)
		{
			TextWriter output = base.Output;
			output.Write("if (");
			base.GenerateExpression(statement.Condition);
			output.Write(")");
			this.OutputStartBrace();
			base.Indent++;
			base.GenerateStatements(statement.TrueStatements);
			base.Indent--;
			global::System.CodeDom.CodeStatementCollection falseStatements = statement.FalseStatements;
			if (falseStatements.Count > 0)
			{
				output.Write('}');
				if (base.Options.ElseOnClosing)
				{
					output.Write(' ');
				}
				else
				{
					output.WriteLine();
				}
				output.Write("else");
				this.OutputStartBrace();
				base.Indent++;
				base.GenerateStatements(falseStatements);
				base.Indent--;
			}
			output.WriteLine('}');
		}

		// Token: 0x0600003F RID: 63 RVA: 0x000204DC File Offset: 0x0001E6DC
		protected override void GenerateTryCatchFinallyStatement(global::System.CodeDom.CodeTryCatchFinallyStatement statement)
		{
			TextWriter output = base.Output;
			global::System.CodeDom.Compiler.CodeGeneratorOptions options = base.Options;
			output.Write("try");
			this.OutputStartBrace();
			base.Indent++;
			base.GenerateStatements(statement.TryStatements);
			base.Indent--;
			foreach (object obj in statement.CatchClauses)
			{
				global::System.CodeDom.CodeCatchClause codeCatchClause = (global::System.CodeDom.CodeCatchClause)obj;
				output.Write('}');
				if (options.ElseOnClosing)
				{
					output.Write(' ');
				}
				else
				{
					output.WriteLine();
				}
				output.Write("catch (");
				this.OutputTypeNamePair(codeCatchClause.CatchExceptionType, this.GetSafeName(codeCatchClause.LocalName));
				output.Write(")");
				this.OutputStartBrace();
				base.Indent++;
				base.GenerateStatements(codeCatchClause.Statements);
				base.Indent--;
			}
			global::System.CodeDom.CodeStatementCollection finallyStatements = statement.FinallyStatements;
			if (finallyStatements.Count > 0)
			{
				output.Write('}');
				if (options.ElseOnClosing)
				{
					output.Write(' ');
				}
				else
				{
					output.WriteLine();
				}
				output.Write("finally");
				this.OutputStartBrace();
				base.Indent++;
				base.GenerateStatements(finallyStatements);
				base.Indent--;
			}
			output.WriteLine('}');
		}

		// Token: 0x06000040 RID: 64 RVA: 0x0002067C File Offset: 0x0001E87C
		protected override void GenerateAssignStatement(global::System.CodeDom.CodeAssignStatement statement)
		{
			TextWriter output = base.Output;
			base.GenerateExpression(statement.Left);
			output.Write(" = ");
			base.GenerateExpression(statement.Right);
			if (this.dont_write_semicolon)
			{
				return;
			}
			output.WriteLine(';');
		}

		// Token: 0x06000041 RID: 65 RVA: 0x000206C8 File Offset: 0x0001E8C8
		protected override void GenerateAttachEventStatement(global::System.CodeDom.CodeAttachEventStatement statement)
		{
			TextWriter output = base.Output;
			this.GenerateEventReferenceExpression(statement.Event);
			output.Write(" += ");
			base.GenerateExpression(statement.Listener);
			output.WriteLine(';');
		}

		// Token: 0x06000042 RID: 66 RVA: 0x00020708 File Offset: 0x0001E908
		protected override void GenerateRemoveEventStatement(global::System.CodeDom.CodeRemoveEventStatement statement)
		{
			TextWriter output = base.Output;
			this.GenerateEventReferenceExpression(statement.Event);
			output.Write(" -= ");
			base.GenerateExpression(statement.Listener);
			output.WriteLine(';');
		}

		// Token: 0x06000043 RID: 67 RVA: 0x00020748 File Offset: 0x0001E948
		protected override void GenerateGotoStatement(global::System.CodeDom.CodeGotoStatement statement)
		{
			TextWriter output = base.Output;
			output.Write("goto ");
			output.Write(this.GetSafeName(statement.Label));
			output.WriteLine(";");
		}

		// Token: 0x06000044 RID: 68 RVA: 0x00020784 File Offset: 0x0001E984
		protected override void GenerateLabeledStatement(global::System.CodeDom.CodeLabeledStatement statement)
		{
			base.Indent--;
			base.Output.Write(statement.Label);
			base.Output.WriteLine(":");
			base.Indent++;
			if (statement.Statement != null)
			{
				base.GenerateStatement(statement.Statement);
			}
		}

		// Token: 0x06000045 RID: 69 RVA: 0x000207E8 File Offset: 0x0001E9E8
		protected override void GenerateVariableDeclarationStatement(global::System.CodeDom.CodeVariableDeclarationStatement statement)
		{
			TextWriter output = base.Output;
			this.OutputTypeNamePair(statement.Type, this.GetSafeName(statement.Name));
			global::System.CodeDom.CodeExpression initExpression = statement.InitExpression;
			if (initExpression != null)
			{
				output.Write(" = ");
				base.GenerateExpression(initExpression);
			}
			if (!this.dont_write_semicolon)
			{
				output.WriteLine(';');
			}
		}

		// Token: 0x06000046 RID: 70 RVA: 0x00020848 File Offset: 0x0001EA48
		protected override void GenerateLinePragmaStart(global::System.CodeDom.CodeLinePragma linePragma)
		{
			base.Output.WriteLine();
			base.Output.Write("#line ");
			base.Output.Write(linePragma.LineNumber);
			base.Output.Write(" \"");
			base.Output.Write(linePragma.FileName);
			base.Output.Write("\"");
			base.Output.WriteLine();
		}

		// Token: 0x06000047 RID: 71 RVA: 0x00002408 File Offset: 0x00000608
		protected override void GenerateLinePragmaEnd(global::System.CodeDom.CodeLinePragma linePragma)
		{
			base.Output.WriteLine();
			base.Output.WriteLine("#line default");
			base.Output.WriteLine("#line hidden");
		}

		// Token: 0x06000048 RID: 72 RVA: 0x000208C0 File Offset: 0x0001EAC0
		protected override void GenerateEvent(global::System.CodeDom.CodeMemberEvent eventRef, global::System.CodeDom.CodeTypeDeclaration declaration)
		{
			if (base.IsCurrentDelegate || base.IsCurrentEnum)
			{
				return;
			}
			this.OutputAttributes(eventRef.CustomAttributes, null, false);
			if (eventRef.PrivateImplementationType == null)
			{
				this.OutputMemberAccessModifier(eventRef.Attributes);
			}
			base.Output.Write("event ");
			if (eventRef.PrivateImplementationType != null)
			{
				this.OutputTypeNamePair(eventRef.Type, eventRef.PrivateImplementationType.BaseType + "." + eventRef.Name);
			}
			else
			{
				this.OutputTypeNamePair(eventRef.Type, this.GetSafeName(eventRef.Name));
			}
			base.Output.WriteLine(';');
		}

		// Token: 0x06000049 RID: 73 RVA: 0x00020978 File Offset: 0x0001EB78
		protected override void GenerateField(global::System.CodeDom.CodeMemberField field)
		{
			if (base.IsCurrentDelegate || base.IsCurrentInterface)
			{
				return;
			}
			TextWriter output = base.Output;
			this.OutputAttributes(field.CustomAttributes, null, false);
			if (base.IsCurrentEnum)
			{
				base.Output.Write(this.GetSafeName(field.Name));
			}
			else
			{
				global::System.CodeDom.MemberAttributes attributes = field.Attributes;
				this.OutputMemberAccessModifier(attributes);
				this.OutputVTableModifier(attributes);
				this.OutputFieldScopeModifier(attributes);
				this.OutputTypeNamePair(field.Type, this.GetSafeName(field.Name));
			}
			global::System.CodeDom.CodeExpression initExpression = field.InitExpression;
			if (initExpression != null)
			{
				output.Write(" = ");
				base.GenerateExpression(initExpression);
			}
			if (base.IsCurrentEnum)
			{
				output.WriteLine(',');
			}
			else
			{
				output.WriteLine(';');
			}
		}

		// Token: 0x0600004A RID: 74 RVA: 0x00002435 File Offset: 0x00000635
		protected override void GenerateSnippetMember(global::System.CodeDom.CodeSnippetTypeMember member)
		{
			base.Output.Write(member.Text);
		}

		// Token: 0x0600004B RID: 75 RVA: 0x00020A4C File Offset: 0x0001EC4C
		protected override void GenerateEntryPointMethod(global::System.CodeDom.CodeEntryPointMethod method, global::System.CodeDom.CodeTypeDeclaration declaration)
		{
			this.OutputAttributes(method.CustomAttributes, null, false);
			base.Output.Write("public static ");
			this.OutputType(method.ReturnType);
			base.Output.Write(" Main()");
			this.OutputStartBrace();
			base.Indent++;
			base.GenerateStatements(method.Statements);
			base.Indent--;
			base.Output.WriteLine("}");
		}

		// Token: 0x0600004C RID: 76 RVA: 0x00020AD4 File Offset: 0x0001ECD4
		protected override void GenerateMethod(global::System.CodeDom.CodeMemberMethod method, global::System.CodeDom.CodeTypeDeclaration declaration)
		{
			if (base.IsCurrentDelegate || base.IsCurrentEnum)
			{
				return;
			}
			TextWriter output = base.Output;
			this.OutputAttributes(method.CustomAttributes, null, false);
			this.OutputAttributes(method.ReturnTypeCustomAttributes, "return: ", false);
			global::System.CodeDom.MemberAttributes attributes = method.Attributes;
			if (!base.IsCurrentInterface)
			{
				if (method.PrivateImplementationType == null)
				{
					this.OutputMemberAccessModifier(attributes);
					this.OutputVTableModifier(attributes);
					this.OutputMemberScopeModifier(attributes);
				}
			}
			else
			{
				this.OutputVTableModifier(attributes);
			}
			this.OutputType(method.ReturnType);
			output.Write(' ');
			global::System.CodeDom.CodeTypeReference privateImplementationType = method.PrivateImplementationType;
			if (privateImplementationType != null)
			{
				output.Write(privateImplementationType.BaseType);
				output.Write('.');
			}
			output.Write(this.GetSafeName(method.Name));
			this.GenerateGenericsParameters(method.TypeParameters);
			output.Write('(');
			this.OutputParameters(method.Parameters);
			output.Write(')');
			this.GenerateGenericsConstraints(method.TypeParameters);
			if (CSharpCodeGenerator.IsAbstract(attributes) || declaration.IsInterface)
			{
				output.WriteLine(';');
			}
			else
			{
				this.OutputStartBrace();
				base.Indent++;
				base.GenerateStatements(method.Statements);
				base.Indent--;
				output.WriteLine('}');
			}
		}

		// Token: 0x0600004D RID: 77 RVA: 0x00002448 File Offset: 0x00000648
		private static bool IsAbstract(global::System.CodeDom.MemberAttributes attributes)
		{
			return (attributes & global::System.CodeDom.MemberAttributes.ScopeMask) == global::System.CodeDom.MemberAttributes.Abstract;
		}

		// Token: 0x0600004E RID: 78 RVA: 0x00020C34 File Offset: 0x0001EE34
		protected override void GenerateProperty(global::System.CodeDom.CodeMemberProperty property, global::System.CodeDom.CodeTypeDeclaration declaration)
		{
			if (base.IsCurrentDelegate || base.IsCurrentEnum)
			{
				return;
			}
			TextWriter output = base.Output;
			this.OutputAttributes(property.CustomAttributes, null, false);
			global::System.CodeDom.MemberAttributes attributes = property.Attributes;
			if (!base.IsCurrentInterface)
			{
				if (property.PrivateImplementationType == null)
				{
					this.OutputMemberAccessModifier(attributes);
					this.OutputVTableModifier(attributes);
					this.OutputMemberScopeModifier(attributes);
				}
			}
			else
			{
				this.OutputVTableModifier(attributes);
			}
			this.OutputType(property.Type);
			output.Write(' ');
			if (!base.IsCurrentInterface && property.PrivateImplementationType != null)
			{
				output.Write(property.PrivateImplementationType.BaseType);
				output.Write('.');
			}
			if (string.Compare(property.Name, "Item", true, CultureInfo.InvariantCulture) == 0 && property.Parameters.Count > 0)
			{
				output.Write("this[");
				this.OutputParameters(property.Parameters);
				output.Write(']');
			}
			else
			{
				output.Write(this.GetSafeName(property.Name));
			}
			this.OutputStartBrace();
			base.Indent++;
			if (declaration.IsInterface || CSharpCodeGenerator.IsAbstract(property.Attributes))
			{
				if (property.HasGet)
				{
					output.WriteLine("get;");
				}
				if (property.HasSet)
				{
					output.WriteLine("set;");
				}
			}
			else
			{
				if (property.HasGet)
				{
					output.Write("get");
					this.OutputStartBrace();
					base.Indent++;
					base.GenerateStatements(property.GetStatements);
					base.Indent--;
					output.WriteLine('}');
				}
				if (property.HasSet)
				{
					output.Write("set");
					this.OutputStartBrace();
					base.Indent++;
					base.GenerateStatements(property.SetStatements);
					base.Indent--;
					output.WriteLine('}');
				}
			}
			base.Indent--;
			output.WriteLine('}');
		}

		// Token: 0x0600004F RID: 79 RVA: 0x00020E60 File Offset: 0x0001F060
		protected override void GenerateConstructor(global::System.CodeDom.CodeConstructor constructor, global::System.CodeDom.CodeTypeDeclaration declaration)
		{
			if (base.IsCurrentDelegate || base.IsCurrentEnum || base.IsCurrentInterface)
			{
				return;
			}
			this.OutputAttributes(constructor.CustomAttributes, null, false);
			this.OutputMemberAccessModifier(constructor.Attributes);
			base.Output.Write(this.GetSafeName(base.CurrentTypeName) + "(");
			this.OutputParameters(constructor.Parameters);
			base.Output.Write(")");
			if (constructor.BaseConstructorArgs.Count > 0)
			{
				base.Output.WriteLine(" : ");
				base.Indent += 2;
				base.Output.Write("base(");
				this.OutputExpressionList(constructor.BaseConstructorArgs);
				base.Output.Write(')');
				base.Indent -= 2;
			}
			if (constructor.ChainedConstructorArgs.Count > 0)
			{
				base.Output.WriteLine(" : ");
				base.Indent += 2;
				base.Output.Write("this(");
				this.OutputExpressionList(constructor.ChainedConstructorArgs);
				base.Output.Write(')');
				base.Indent -= 2;
			}
			this.OutputStartBrace();
			base.Indent++;
			base.GenerateStatements(constructor.Statements);
			base.Indent--;
			base.Output.WriteLine('}');
		}

		// Token: 0x06000050 RID: 80 RVA: 0x00020FF0 File Offset: 0x0001F1F0
		protected override void GenerateTypeConstructor(global::System.CodeDom.CodeTypeConstructor constructor)
		{
			if (base.IsCurrentDelegate || base.IsCurrentEnum || base.IsCurrentInterface)
			{
				return;
			}
			this.OutputAttributes(constructor.CustomAttributes, null, false);
			base.Output.Write("static " + this.GetSafeName(base.CurrentTypeName) + "()");
			this.OutputStartBrace();
			base.Indent++;
			base.GenerateStatements(constructor.Statements);
			base.Indent--;
			base.Output.WriteLine('}');
		}

		// Token: 0x06000051 RID: 81 RVA: 0x00021090 File Offset: 0x0001F290
		protected override void GenerateTypeStart(global::System.CodeDom.CodeTypeDeclaration declaration)
		{
			TextWriter output = base.Output;
			this.OutputAttributes(declaration.CustomAttributes, null, false);
			if (!base.IsCurrentDelegate)
			{
				this.OutputTypeAttributes(declaration);
				output.Write(this.GetSafeName(declaration.Name));
				this.GenerateGenericsParameters(declaration.TypeParameters);
				IEnumerator enumerator = declaration.BaseTypes.GetEnumerator();
				if (enumerator.MoveNext())
				{
					global::System.CodeDom.CodeTypeReference codeTypeReference = (global::System.CodeDom.CodeTypeReference)enumerator.Current;
					output.Write(" : ");
					this.OutputType(codeTypeReference);
					while (enumerator.MoveNext())
					{
						object obj = enumerator.Current;
						codeTypeReference = (global::System.CodeDom.CodeTypeReference)obj;
						output.Write(", ");
						this.OutputType(codeTypeReference);
					}
				}
				this.GenerateGenericsConstraints(declaration.TypeParameters);
				this.OutputStartBrace();
				base.Indent++;
			}
			else
			{
				if ((declaration.TypeAttributes & TypeAttributes.VisibilityMask) == TypeAttributes.Public)
				{
					output.Write("public ");
				}
				global::System.CodeDom.CodeTypeDelegate codeTypeDelegate = (global::System.CodeDom.CodeTypeDelegate)declaration;
				output.Write("delegate ");
				this.OutputType(codeTypeDelegate.ReturnType);
				output.Write(" ");
				output.Write(this.GetSafeName(declaration.Name));
				output.Write("(");
				this.OutputParameters(codeTypeDelegate.Parameters);
				output.WriteLine(");");
			}
		}

		// Token: 0x06000052 RID: 82 RVA: 0x00002451 File Offset: 0x00000651
		protected override void GenerateTypeEnd(global::System.CodeDom.CodeTypeDeclaration declaration)
		{
			if (!base.IsCurrentDelegate)
			{
				base.Indent--;
				base.Output.WriteLine("}");
			}
		}

		// Token: 0x06000053 RID: 83 RVA: 0x000211E0 File Offset: 0x0001F3E0
		protected override void GenerateNamespaceStart(global::System.CodeDom.CodeNamespace ns)
		{
			TextWriter output = base.Output;
			string name = ns.Name;
			if (name != null && name.Length != 0)
			{
				output.Write("namespace ");
				output.Write(this.GetSafeName(name));
				this.OutputStartBrace();
				base.Indent++;
			}
		}

		// Token: 0x06000054 RID: 84 RVA: 0x00021238 File Offset: 0x0001F438
		protected override void GenerateNamespaceEnd(global::System.CodeDom.CodeNamespace ns)
		{
			string name = ns.Name;
			if (name != null && name.Length != 0)
			{
				base.Indent--;
				base.Output.WriteLine("}");
			}
		}

		// Token: 0x06000055 RID: 85 RVA: 0x0002127C File Offset: 0x0001F47C
		protected override void GenerateNamespaceImport(global::System.CodeDom.CodeNamespaceImport import)
		{
			TextWriter output = base.Output;
			output.Write("using ");
			output.Write(this.GetSafeName(import.Namespace));
			output.WriteLine(';');
		}

		// Token: 0x06000056 RID: 86 RVA: 0x0000247C File Offset: 0x0000067C
		protected override void GenerateAttributeDeclarationsStart(global::System.CodeDom.CodeAttributeDeclarationCollection attributes)
		{
			base.Output.Write('[');
		}

		// Token: 0x06000057 RID: 87 RVA: 0x0000248B File Offset: 0x0000068B
		protected override void GenerateAttributeDeclarationsEnd(global::System.CodeDom.CodeAttributeDeclarationCollection attributes)
		{
			base.Output.Write(']');
		}

		// Token: 0x06000058 RID: 88 RVA: 0x000212B8 File Offset: 0x0001F4B8
		private void OutputStartBrace()
		{
			if (base.Options.BracingStyle == "C")
			{
				base.Output.WriteLine(string.Empty);
				base.Output.WriteLine("{");
			}
			else
			{
				base.Output.WriteLine(" {");
			}
		}

		// Token: 0x06000059 RID: 89 RVA: 0x00021314 File Offset: 0x0001F514
		private void OutputAttributes(global::System.CodeDom.CodeAttributeDeclarationCollection attributes, string prefix, bool inline)
		{
			bool flag = false;
			foreach (object obj in attributes)
			{
				global::System.CodeDom.CodeAttributeDeclaration codeAttributeDeclaration = (global::System.CodeDom.CodeAttributeDeclaration)obj;
				if (codeAttributeDeclaration.Name == "System.ParamArrayAttribute")
				{
					flag = true;
				}
				else
				{
					this.GenerateAttributeDeclarationsStart(attributes);
					if (prefix != null)
					{
						base.Output.Write(prefix);
					}
					this.OutputAttributeDeclaration(codeAttributeDeclaration);
					this.GenerateAttributeDeclarationsEnd(attributes);
					if (inline)
					{
						base.Output.Write(" ");
					}
					else
					{
						base.Output.WriteLine();
					}
				}
			}
			if (flag)
			{
				if (prefix != null)
				{
					base.Output.Write(prefix);
				}
				base.Output.Write("params");
				if (inline)
				{
					base.Output.Write(" ");
				}
				else
				{
					base.Output.WriteLine();
				}
			}
		}

		// Token: 0x0600005A RID: 90 RVA: 0x00021424 File Offset: 0x0001F624
		private void OutputAttributeDeclaration(global::System.CodeDom.CodeAttributeDeclaration attribute)
		{
			base.Output.Write(attribute.Name.Replace('+', '.'));
			base.Output.Write('(');
			IEnumerator enumerator = attribute.Arguments.GetEnumerator();
			if (enumerator.MoveNext())
			{
				global::System.CodeDom.CodeAttributeArgument codeAttributeArgument = (global::System.CodeDom.CodeAttributeArgument)enumerator.Current;
				this.OutputAttributeArgument(codeAttributeArgument);
				while (enumerator.MoveNext())
				{
					base.Output.Write(", ");
					codeAttributeArgument = (global::System.CodeDom.CodeAttributeArgument)enumerator.Current;
					this.OutputAttributeArgument(codeAttributeArgument);
				}
			}
			base.Output.Write(')');
		}

		// Token: 0x0600005B RID: 91 RVA: 0x0000249A File Offset: 0x0000069A
		protected override void OutputType(global::System.CodeDom.CodeTypeReference type)
		{
			base.Output.Write(this.GetTypeOutput(type));
		}

		// Token: 0x0600005C RID: 92 RVA: 0x000024AE File Offset: 0x000006AE
		private void OutputVTableModifier(global::System.CodeDom.MemberAttributes attributes)
		{
			if ((attributes & global::System.CodeDom.MemberAttributes.VTableMask) == global::System.CodeDom.MemberAttributes.New)
			{
				base.Output.Write("new ");
			}
		}

		// Token: 0x0600005D RID: 93 RVA: 0x000214C4 File Offset: 0x0001F6C4
		protected override void OutputFieldScopeModifier(global::System.CodeDom.MemberAttributes attributes)
		{
			switch (attributes & global::System.CodeDom.MemberAttributes.ScopeMask)
			{
			case global::System.CodeDom.MemberAttributes.Static:
				base.Output.Write("static ");
				break;
			case global::System.CodeDom.MemberAttributes.Const:
				base.Output.Write("const ");
				break;
			}
		}

		// Token: 0x0600005E RID: 94 RVA: 0x0002151C File Offset: 0x0001F71C
		protected override void OutputMemberAccessModifier(global::System.CodeDom.MemberAttributes attributes)
		{
			global::System.CodeDom.MemberAttributes memberAttributes = attributes & global::System.CodeDom.MemberAttributes.AccessMask;
			if (memberAttributes != global::System.CodeDom.MemberAttributes.Assembly && memberAttributes != global::System.CodeDom.MemberAttributes.FamilyAndAssembly)
			{
				if (memberAttributes != global::System.CodeDom.MemberAttributes.Family)
				{
					if (memberAttributes != global::System.CodeDom.MemberAttributes.FamilyOrAssembly)
					{
						if (memberAttributes != global::System.CodeDom.MemberAttributes.Private)
						{
							if (memberAttributes == global::System.CodeDom.MemberAttributes.Public)
							{
								base.Output.Write("public ");
							}
						}
						else
						{
							base.Output.Write("private ");
						}
					}
					else
					{
						base.Output.Write("protected internal ");
					}
				}
				else
				{
					base.Output.Write("protected ");
				}
			}
			else
			{
				base.Output.Write("internal ");
			}
		}

		// Token: 0x0600005F RID: 95 RVA: 0x000215E4 File Offset: 0x0001F7E4
		protected override void OutputMemberScopeModifier(global::System.CodeDom.MemberAttributes attributes)
		{
			switch (attributes & global::System.CodeDom.MemberAttributes.ScopeMask)
			{
			case global::System.CodeDom.MemberAttributes.Abstract:
				base.Output.Write("abstract ");
				break;
			case global::System.CodeDom.MemberAttributes.Final:
				break;
			case global::System.CodeDom.MemberAttributes.Static:
				base.Output.Write("static ");
				break;
			case global::System.CodeDom.MemberAttributes.Override:
				base.Output.Write("override ");
				break;
			default:
			{
				global::System.CodeDom.MemberAttributes memberAttributes = attributes & global::System.CodeDom.MemberAttributes.AccessMask;
				if (memberAttributes == global::System.CodeDom.MemberAttributes.Assembly || memberAttributes == global::System.CodeDom.MemberAttributes.Family || memberAttributes == global::System.CodeDom.MemberAttributes.Public)
				{
					base.Output.Write("virtual ");
				}
				break;
			}
			}
		}

		// Token: 0x06000060 RID: 96 RVA: 0x00021698 File Offset: 0x0001F898
		private void OutputTypeAttributes(global::System.CodeDom.CodeTypeDeclaration declaration)
		{
			TextWriter output = base.Output;
			TypeAttributes typeAttributes = declaration.TypeAttributes;
			switch (typeAttributes & TypeAttributes.VisibilityMask)
			{
			case TypeAttributes.NotPublic:
			case TypeAttributes.NestedAssembly:
			case TypeAttributes.NestedFamANDAssem:
				output.Write("internal ");
				break;
			case TypeAttributes.Public:
			case TypeAttributes.NestedPublic:
				output.Write("public ");
				break;
			case TypeAttributes.NestedPrivate:
				output.Write("private ");
				break;
			case TypeAttributes.NestedFamily:
				output.Write("protected ");
				break;
			case TypeAttributes.VisibilityMask:
				output.Write("protected internal ");
				break;
			}
			if (declaration.IsStruct)
			{
				if (declaration.IsPartial)
				{
					output.Write("partial ");
				}
				output.Write("struct ");
			}
			else if (declaration.IsEnum)
			{
				output.Write("enum ");
			}
			else if ((typeAttributes & TypeAttributes.ClassSemanticsMask) != TypeAttributes.NotPublic)
			{
				if (declaration.IsPartial)
				{
					output.Write("partial ");
				}
				output.Write("interface ");
			}
			else
			{
				if ((typeAttributes & TypeAttributes.Sealed) != TypeAttributes.NotPublic)
				{
					output.Write("sealed ");
				}
				if ((typeAttributes & TypeAttributes.Abstract) != TypeAttributes.NotPublic)
				{
					output.Write("abstract ");
				}
				if (declaration.IsPartial)
				{
					output.Write("partial ");
				}
				output.Write("class ");
			}
		}

		// Token: 0x06000061 RID: 97 RVA: 0x000217FC File Offset: 0x0001F9FC
		[global::System.MonoTODO("Implement missing special characters")]
		protected override string QuoteSnippetString(string value)
		{
			string text = value.Replace("\\", "\\\\");
			text = text.Replace("\"", "\\\"");
			text = text.Replace("\t", "\\t");
			text = text.Replace("\r", "\\r");
			text = text.Replace("\n", "\\n");
			return "\"" + text + "\"";
		}

		// Token: 0x06000062 RID: 98 RVA: 0x00021870 File Offset: 0x0001FA70
		protected override void GeneratePrimitiveExpression(global::System.CodeDom.CodePrimitiveExpression e)
		{
			if (e.Value is char)
			{
				this.GenerateCharValue((char)e.Value);
			}
			else if (e.Value is ushort)
			{
				ushort num = (ushort)e.Value;
				base.Output.Write(num.ToString(CultureInfo.InvariantCulture));
			}
			else if (e.Value is uint)
			{
				uint num2 = (uint)e.Value;
				base.Output.Write(num2.ToString(CultureInfo.InvariantCulture));
				base.Output.Write("u");
			}
			else if (e.Value is ulong)
			{
				ulong num3 = (ulong)e.Value;
				base.Output.Write(num3.ToString(CultureInfo.InvariantCulture));
				base.Output.Write("ul");
			}
			else if (e.Value is sbyte)
			{
				sbyte b = (sbyte)e.Value;
				base.Output.Write(b.ToString(CultureInfo.InvariantCulture));
			}
			else
			{
				base.GeneratePrimitiveExpression(e);
			}
		}

		// Token: 0x06000063 RID: 99 RVA: 0x000219AC File Offset: 0x0001FBAC
		private void GenerateCharValue(char c)
		{
			base.Output.Write('\'');
			switch (c)
			{
			case '\t':
				base.Output.Write("\\t");
				break;
			case '\n':
				base.Output.Write("\\n");
				break;
			default:
				if (c != '\u2028')
				{
					if (c != '\u2029')
					{
						if (c != '\0')
						{
							if (c != '"')
							{
								if (c != '\'')
								{
									if (c != '\\')
									{
										base.Output.Write(c);
									}
									else
									{
										base.Output.Write("\\\\");
									}
								}
								else
								{
									base.Output.Write("\\'");
								}
							}
							else
							{
								base.Output.Write("\\\"");
							}
						}
						else
						{
							base.Output.Write("\\0");
						}
					}
					else
					{
						base.Output.Write("\\u");
						TextWriter output = base.Output;
						int num = (int)c;
						output.Write(num.ToString("X4", CultureInfo.InvariantCulture));
					}
				}
				else
				{
					base.Output.Write("\\u");
					TextWriter output2 = base.Output;
					int num2 = (int)c;
					output2.Write(num2.ToString("X4", CultureInfo.InvariantCulture));
				}
				break;
			case '\r':
				base.Output.Write("\\r");
				break;
			}
			base.Output.Write('\'');
		}

		// Token: 0x06000064 RID: 100 RVA: 0x000024CE File Offset: 0x000006CE
		protected override void GenerateSingleFloatValue(float f)
		{
			base.GenerateSingleFloatValue(f);
			base.Output.Write('F');
		}

		// Token: 0x06000065 RID: 101 RVA: 0x000024E4 File Offset: 0x000006E4
		protected override void GenerateDecimalValue(decimal d)
		{
			base.GenerateDecimalValue(d);
			base.Output.Write('m');
		}

		// Token: 0x06000066 RID: 102 RVA: 0x00021B38 File Offset: 0x0001FD38
		protected override void GenerateParameterDeclarationExpression(global::System.CodeDom.CodeParameterDeclarationExpression e)
		{
			this.OutputAttributes(e.CustomAttributes, null, true);
			this.OutputDirection(e.Direction);
			this.OutputType(e.Type);
			base.Output.Write(' ');
			base.Output.Write(this.GetSafeName(e.Name));
		}

		// Token: 0x06000067 RID: 103 RVA: 0x000024FA File Offset: 0x000006FA
		protected override void GenerateTypeOfExpression(global::System.CodeDom.CodeTypeOfExpression e)
		{
			base.Output.Write("typeof(");
			this.OutputType(e.Type);
			base.Output.Write(")");
		}

		// Token: 0x06000068 RID: 104 RVA: 0x00002528 File Offset: 0x00000728
		protected override string CreateEscapedIdentifier(string value)
		{
			if (value == null)
			{
				throw new NullReferenceException("Argument identifier is null.");
			}
			return this.GetSafeName(value);
		}

		// Token: 0x06000069 RID: 105 RVA: 0x00002542 File Offset: 0x00000742
		protected override string CreateValidIdentifier(string value)
		{
			if (value == null)
			{
				throw new NullReferenceException();
			}
			if (CSharpCodeGenerator.keywordsTable == null)
			{
				CSharpCodeGenerator.FillKeywordTable();
			}
			if (CSharpCodeGenerator.keywordsTable.Contains(value))
			{
				return "_" + value;
			}
			return value;
		}

		// Token: 0x0600006A RID: 106 RVA: 0x00021B90 File Offset: 0x0001FD90
		protected override string GetTypeOutput(global::System.CodeDom.CodeTypeReference type)
		{
			if ((type.Options & global::System.CodeDom.CodeTypeReferenceOptions.GenericTypeParameter) != (global::System.CodeDom.CodeTypeReferenceOptions)0)
			{
				return type.BaseType;
			}
			string text;
			if (type.ArrayElementType != null)
			{
				text = this.GetTypeOutput(type.ArrayElementType);
			}
			else
			{
				text = this.DetermineTypeOutput(type);
			}
			int i = type.ArrayRank;
			if (i > 0)
			{
				text += '[';
				for (i--; i > 0; i--)
				{
					text += ',';
				}
				text += ']';
			}
			return text;
		}

		// Token: 0x0600006B RID: 107 RVA: 0x00021C28 File Offset: 0x0001FE28
		private string DetermineTypeOutput(global::System.CodeDom.CodeTypeReference type)
		{
			string baseType = type.BaseType;
			string text = baseType.ToLower(CultureInfo.InvariantCulture);
			switch (text)
			{
			case "system.int32":
				return "int";
			case "system.int64":
				return "long";
			case "system.int16":
				return "short";
			case "system.boolean":
				return "bool";
			case "system.char":
				return "char";
			case "system.string":
				return "string";
			case "system.object":
				return "object";
			case "system.void":
				return "void";
			case "system.byte":
				return "byte";
			case "system.sbyte":
				return "sbyte";
			case "system.decimal":
				return "decimal";
			case "system.double":
				return "double";
			case "system.single":
				return "float";
			case "system.uint16":
				return "ushort";
			case "system.uint32":
				return "uint";
			case "system.uint64":
				return "ulong";
			}
			StringBuilder stringBuilder = new StringBuilder(baseType.Length);
			if (type.Options == global::System.CodeDom.CodeTypeReferenceOptions.GlobalReference)
			{
				stringBuilder.Append("global::");
			}
			int num2 = 0;
			for (int i = 0; i < baseType.Length; i++)
			{
				char c = baseType[i];
				if (c != '+' && c != '.')
				{
					if (c == '`')
					{
						stringBuilder.Append(this.CreateEscapedIdentifier(baseType.Substring(num2, i - num2)));
						i++;
						int num3 = i;
						while (num3 < baseType.Length && char.IsDigit(baseType[num3]))
						{
							num3++;
						}
						int num4 = int.Parse(baseType.Substring(i, num3 - i));
						this.OutputTypeArguments(type.TypeArguments, stringBuilder, num4);
						i = num3;
						if (i < baseType.Length && (baseType[i] == '+' || baseType[i] == '.'))
						{
							stringBuilder.Append('.');
							i++;
						}
						num2 = i;
					}
				}
				else
				{
					stringBuilder.Append(this.CreateEscapedIdentifier(baseType.Substring(num2, i - num2)));
					stringBuilder.Append('.');
					i++;
					num2 = i;
				}
			}
			if (num2 < baseType.Length)
			{
				stringBuilder.Append(this.CreateEscapedIdentifier(baseType.Substring(num2)));
			}
			return stringBuilder.ToString();
		}

		// Token: 0x0600006C RID: 108 RVA: 0x0000257C File Offset: 0x0000077C
		private static bool is_identifier_start_character(char c)
		{
			return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == '_' || c == '@' || char.IsLetter(c);
		}

		// Token: 0x0600006D RID: 109 RVA: 0x00021FC4 File Offset: 0x000201C4
		private static bool is_identifier_part_character(char c)
		{
			return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == '_' || (c >= '0' && c <= '9') || char.IsLetter(c);
		}

		// Token: 0x0600006E RID: 110 RVA: 0x00022014 File Offset: 0x00020214
		protected override bool IsValidIdentifier(string identifier)
		{
			if (identifier == null || identifier.Length == 0)
			{
				return false;
			}
			if (CSharpCodeGenerator.keywordsTable == null)
			{
				CSharpCodeGenerator.FillKeywordTable();
			}
			if (CSharpCodeGenerator.keywordsTable.Contains(identifier))
			{
				return false;
			}
			if (!CSharpCodeGenerator.is_identifier_start_character(identifier[0]))
			{
				return false;
			}
			for (int i = 1; i < identifier.Length; i++)
			{
				if (!CSharpCodeGenerator.is_identifier_part_character(identifier[i]))
				{
					return false;
				}
			}
			return true;
		}

		// Token: 0x0600006F RID: 111 RVA: 0x000025B7 File Offset: 0x000007B7
		protected override bool Supports(global::System.CodeDom.Compiler.GeneratorSupport supports)
		{
			return true;
		}

		// Token: 0x06000070 RID: 112 RVA: 0x00022094 File Offset: 0x00020294
		protected override void GenerateDirectives(global::System.CodeDom.CodeDirectiveCollection directives)
		{
			foreach (object obj in directives)
			{
				global::System.CodeDom.CodeDirective codeDirective = (global::System.CodeDom.CodeDirective)obj;
				if (codeDirective is global::System.CodeDom.CodeChecksumPragma)
				{
					this.GenerateCodeChecksumPragma((global::System.CodeDom.CodeChecksumPragma)codeDirective);
				}
				else
				{
					if (!(codeDirective is global::System.CodeDom.CodeRegionDirective))
					{
						throw new NotImplementedException("Unknown CodeDirective");
					}
					this.GenerateCodeRegionDirective((global::System.CodeDom.CodeRegionDirective)codeDirective);
				}
			}
		}

		// Token: 0x06000071 RID: 113 RVA: 0x00022130 File Offset: 0x00020330
		private void GenerateCodeChecksumPragma(global::System.CodeDom.CodeChecksumPragma pragma)
		{
			base.Output.Write("#pragma checksum ");
			base.Output.Write(this.QuoteSnippetString(pragma.FileName));
			base.Output.Write(" \"");
			base.Output.Write(pragma.ChecksumAlgorithmId.ToString("B"));
			base.Output.Write("\" \"");
			if (pragma.ChecksumData != null)
			{
				foreach (byte b in pragma.ChecksumData)
				{
					base.Output.Write(b.ToString("X2"));
				}
			}
			base.Output.WriteLine("\"");
		}

		// Token: 0x06000072 RID: 114 RVA: 0x000221F4 File Offset: 0x000203F4
		private void GenerateCodeRegionDirective(global::System.CodeDom.CodeRegionDirective region)
		{
			global::System.CodeDom.CodeRegionMode regionMode = region.RegionMode;
			if (regionMode == global::System.CodeDom.CodeRegionMode.Start)
			{
				base.Output.Write("#region ");
				base.Output.WriteLine(region.RegionText);
				return;
			}
			if (regionMode != global::System.CodeDom.CodeRegionMode.End)
			{
				return;
			}
			base.Output.WriteLine("#endregion");
		}

		// Token: 0x06000073 RID: 115 RVA: 0x00022250 File Offset: 0x00020450
		private void GenerateGenericsParameters(global::System.CodeDom.CodeTypeParameterCollection parameters)
		{
			int count = parameters.Count;
			if (count == 0)
			{
				return;
			}
			base.Output.Write('<');
			for (int i = 0; i < count - 1; i++)
			{
				base.Output.Write(parameters[i].Name);
				base.Output.Write(", ");
			}
			base.Output.Write(parameters[count - 1].Name);
			base.Output.Write('>');
		}

		// Token: 0x06000074 RID: 116 RVA: 0x000222DC File Offset: 0x000204DC
		private void GenerateGenericsConstraints(global::System.CodeDom.CodeTypeParameterCollection parameters)
		{
			int count = parameters.Count;
			if (count == 0)
			{
				return;
			}
			bool flag = false;
			for (int i = 0; i < count; i++)
			{
				global::System.CodeDom.CodeTypeParameter codeTypeParameter = parameters[i];
				bool flag2 = codeTypeParameter.Constraints.Count != 0;
				base.Output.WriteLine();
				if (flag2 || codeTypeParameter.HasConstructorConstraint)
				{
					if (!flag)
					{
						base.Indent++;
						flag = true;
					}
					base.Output.Write("where ");
					base.Output.Write(codeTypeParameter.Name);
					base.Output.Write(" : ");
					for (int j = 0; j < codeTypeParameter.Constraints.Count; j++)
					{
						if (j > 0)
						{
							base.Output.Write(", ");
						}
						this.OutputType(codeTypeParameter.Constraints[j]);
					}
					if (codeTypeParameter.HasConstructorConstraint)
					{
						if (flag2)
						{
							base.Output.Write(", ");
						}
						base.Output.Write("new");
						if (flag2)
						{
							base.Output.Write(" ");
						}
						base.Output.Write("()");
					}
				}
			}
			if (flag)
			{
				base.Indent--;
			}
		}

		// Token: 0x06000075 RID: 117 RVA: 0x00022448 File Offset: 0x00020648
		private string GetTypeArguments(global::System.CodeDom.CodeTypeReferenceCollection collection)
		{
			StringBuilder stringBuilder = new StringBuilder(" <");
			foreach (object obj in collection)
			{
				global::System.CodeDom.CodeTypeReference codeTypeReference = (global::System.CodeDom.CodeTypeReference)obj;
				stringBuilder.Append(this.GetTypeOutput(codeTypeReference));
				stringBuilder.Append(", ");
			}
			stringBuilder.Length--;
			stringBuilder[stringBuilder.Length - 1] = '>';
			return stringBuilder.ToString();
		}

		// Token: 0x06000076 RID: 118 RVA: 0x000224E8 File Offset: 0x000206E8
		private void OutputTypeArguments(global::System.CodeDom.CodeTypeReferenceCollection typeArguments, StringBuilder sb, int count)
		{
			if (count == 0)
			{
				return;
			}
			if (typeArguments.Count == 0)
			{
				sb.Append("<>");
				return;
			}
			sb.Append('<');
			sb.Append(this.GetTypeOutput(typeArguments[0]));
			for (int i = 1; i < count; i++)
			{
				sb.Append(", ");
				sb.Append(this.GetTypeOutput(typeArguments[i]));
			}
			sb.Append('>');
		}

		// Token: 0x06000077 RID: 119 RVA: 0x000025BA File Offset: 0x000007BA
		private string GetSafeName(string id)
		{
			if (CSharpCodeGenerator.keywordsTable == null)
			{
				CSharpCodeGenerator.FillKeywordTable();
			}
			if (CSharpCodeGenerator.keywordsTable.Contains(id))
			{
				return "@" + id;
			}
			return id;
		}

		// Token: 0x06000078 RID: 120 RVA: 0x0002256C File Offset: 0x0002076C
		private static void FillKeywordTable()
		{
			CSharpCodeGenerator.keywordsTable = new Hashtable();
			foreach (string text in CSharpCodeGenerator.keywords)
			{
				CSharpCodeGenerator.keywordsTable.Add(text, text);
			}
		}

		// Token: 0x04000025 RID: 37
		private IDictionary<string, string> providerOptions;

		// Token: 0x04000026 RID: 38
		private bool dont_write_semicolon;

		// Token: 0x04000027 RID: 39
		private static Hashtable keywordsTable;

		// Token: 0x04000028 RID: 40
		private static string[] keywords = new string[]
		{
			"abstract", "event", "new", "struct", "as", "explicit", "null", "switch", "base", "extern",
			"this", "false", "operator", "throw", "break", "finally", "out", "true", "fixed", "override",
			"try", "case", "params", "typeof", "catch", "for", "private", "foreach", "protected", "checked",
			"goto", "public", "unchecked", "class", "if", "readonly", "unsafe", "const", "implicit", "ref",
			"continue", "in", "return", "using", "virtual", "default", "interface", "sealed", "volatile", "delegate",
			"internal", "do", "is", "sizeof", "while", "lock", "stackalloc", "else", "static", "enum",
			"namespace", "object", "bool", "byte", "float", "uint", "char", "ulong", "ushort", "decimal",
			"int", "sbyte", "short", "double", "long", "string", "void", "partial", "yield", "where"
		};
	}
}
